### PR TITLE
cmd/rofl/deploy: Add --replace-machine flag and show native pricing

### LINKED ISSUE #487: `rofl deploy` figure out what to do when the machine expires
A common scenario at the hackathon:
1. create, build and deploy ROFL app
2. the machine instance expires in 1 hour
3. they run `oasis rofl deploy` and get
   ```
   Using provider: oasis1qp2ens0hsp7gh23wajxa4hpetkdek3swyyulyrmz    (oasis1qp2ens0hsp7gh23wajxa4hpetkdek3swyyulyrmz)
   Pushing ROFL app to OCI repository 'rofl.sh/f2549623-79b6-4629-b5a5-7a86f7cc8b07:1749071756'...
   Deploying into existing machine: 00000000000000bb
   Error: instance not found
   ```
   becuase the `00000000000000bb` machine expired on-chain.

Solution for the hackathoners: Remove the `machines` section from `rofl.yaml` and redeploy it.

IRL though, what would be the best devex flow in this case? Add a parameter `-f` (`--redeploy`, `-re-rent`?) to rent a new machine and overwrite the machine sections in rofl.yaml? Or require user to run `oasis rofl machine remove`, but in this case the machine is not there yet, so this will fail (use `-f` or `--offline`?). Also, since the machine state probably didn't go away yet (some grace period?), would it work, if the developer would just top-up his provider?

### PR DESCRIPTION
**Pull request by abukosek**
Closes #487 and #508.

### CODE REVIEW

File: cmd/rofl/deploy.go [hunk 1]
```diff
@@ -353,8 +371,31 @@ func showProviderOffer(offer *roflmarket.Offer) {
...
+			default:
+				t = "<unknown>"
+			}
+
+			if gotPrev {
+				fmt.Printf(" | ")
+			}
 
-	// TODO: Show pricing.
+			fmt.Printf("%s %s/%s", price.String(), offer.Payment.Native.Denomination.String(), t)
```
Comment (matevz) [inline cmd/rofl/deploy.go:394]: You'll need to use the native token prettifiers.

```
$ oasis rofl deploy --deployment mainnet --show-offers
Using provider: oasis1qzc8pldvm8vm3duvdrj63wgvkw34y9ucfcxzetqr (oasis1qzc8pldvm8vm3duvdrj63wgvkw34y9ucfcxzetqr)

Offers available from the selected provider:
- large [0000000000000002]
  TEE: tdx | Memory: 8192 MiB | vCPUs: 4 | Storage: 156.25 GiB
  Price: 9000000000000000000 <native>/hour | 7800000000000000000000 <native>/month

- medium [0000000000000001]
  TEE: tdx | Memory: 4096 MiB | vCPUs: 2 | Storage: 78.12 GiB
  Price: 5000000000000000000 <native>/hour | 3900000000000000000000 <native>/month

- small [0000000000000000]
  TEE: tdx | Memory: 2048 MiB | vCPUs: 1 | Storage: 39.06 GiB
  Price: 3000000000000000000 <native>/hour | 2000000000000000000000 <native>/month
```

Comment (abukosek) [reply cmd/rofl/deploy.go]: Oops, fixed :)

File: cmd/rofl/deploy.go [hunk 2]
```diff
@@ -233,13 +236,34 @@ var (
...
 				sigTx, meta, err = common.SignParaTimeTransaction(ctx, npa, acc, conn, tx, nil)
+				if strings.Contains(err.Error(), "instance not found") {
+					if deployReplaceMachine {
+						fmt.Printf("Machine instance not found. Obtaining new one...")
+						machine, err = obtainMachine()
+						cobra.CheckErr(err)
+						return doDeployMachine(machine)
+					}
+
+					cobra.CheckErr("Machine instance not found. If your instance expired, run this command with --replace-machine flag to replace it with a new machine.")
```
Comment (matevz) [inline cmd/rofl/deploy.go:247]:
```suggestion
					cobra.CheckErr("Machine instance not found.\nHint: If your instance expired, run this command with --replace-machine flag to replace it with a new machine.")
```

Comment (matevz) [reply cmd/rofl/deploy.go]: We use "tips" when we try to guess why the error happened, see https://github.com/oasisprotocol/cli/blob/master/cmd/common/transaction.go#L573-L597

Comment (abukosek) [reply cmd/rofl/deploy.go]: OK, I've changed it :)  But note that if this error is ever moved outside of `cobra.CheckErr` (e.g. by returning it and/or formatting it with `fmt.Errorf`), the linter will complain about the newline and the capitalization.  We could disable that linter check if we prefer this style.

**Review by matevz — APPROVED** [review]
