### PR TITLE
Fix artifact upgrade and bump rofl-containers

### LINKED ISSUE #576: `rofl upgrade` should not overwrite unchanged artifacts
Currently running `rofl upgrade` will result in some artifacts that are not part of the upgrade (eg. `builder` and `compose`) to be incorrectly overwritten.

### PR DESCRIPTION
**Pull request by kostko**
Closes #576

### CODE REVIEW

File: build/rofl/manifest.go [hunk 1]
```diff
@@ -500,10 +500,55 @@ type ArtifactsConfig struct {
...
+	}
+	return changed
+}
+
+// UpgradeTo upgrades the artifacts to the latest version by updating any relevant fields.
+//
+// Returns true iff any artifacts have been updated.
+func (ac *ArtifactsConfig) UpgradeTo(latest *ArtifactsConfig) bool {
+	var changed bool
+	changed = upgradeArtifacts([]artifactUpgrade{
```
Comment (ptrus) [inline build/rofl/manifest.go:528]: `|| changed` is unneeded here.

**Review by ptrus — APPROVED** [review]
